name: Foodgram CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  backend_docker:
    name: Build and push backend
    runs-on: ubuntu-latest
    needs: [frontend_docker]
    if: github.event_name == 'push'

    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Configure Docker environment
        uses: docker/setup-buildx-action@v2

      - name: Authenticate with Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_backend:latest

  frontend_docker:
    name: Build and push frontend
    runs-on: ubuntu-latest
    needs: [nginx_docker]
    if: github.event_name == 'push'

    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Configure Docker environment
        uses: docker/setup-buildx-action@v2

      - name: Authenticate with Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_frontend:latest

  nginx_docker:
    name: Build and push nginx
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Configure Docker environment
        uses: docker/setup-buildx-action@v2

      - name: Authenticate with Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push nginx image
        uses: docker/build-push-action@v4
        with:
          context: ./infra
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_nginx:latest
